spring:
  application:
    name: naive-rag
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/naive
    username: postgres
    password: 140503
    driver-class-name: org.postgresql.Driver
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  # Flyway Migration Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false
  # AI Configuration
  ai:
    chat:
      client:
        enabled: true
      memory:
        repository:
          jdbc:
            initialize-schema: always
    openai:
      api-key: ${MODEL_API_KEY}
      base-url: https://integrate.api.nvidia.com/v1
      chat:
        model: nvidia/nemotron-3-ultra-550b-a55b
        temperature: 0.7
        max-tokens: 8192
      embedding:
        api-key: ${EMBEDDING_API_KEY}
        base-url: https://integrate.api.nvidia.com/v1
        model: nvidia/nemotron-3-embed-1b
        dimensions: 2048
    # Vector DB Configuration
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        api-key: ${VECTOR_API_KEY}
        collection-name: vector_store
        content-field-name: doc_content
        use-tls: false
        initialize-schema: true
# Logging Configuration
logging:
  file:
    name: logs/access-hub.log
  level:
    root: INFO
    com.pranit.accesshub: DEBUG
# SafeGuard Configuration
ai:
  advisor:
    safeguard:
      blocked-words:
        - password
        - secret-key
        - api-key
        - access-token
        - refresh-token
        - private-key
        - client-secret
        - credentials
# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
info:
  app:
    name: access-hub
    description: "This is an RAG Service"
    version: "1.0.0"